version: "3"
services:
  users_db:
    image: mongo:7.0

  realtime:
    build:
      context: .
      dockerfile: ./apps/real-time-server/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - USERS_DB_URI=mongodb://users_db:27017
      - USERS_DB_NAME=usersDB

  registry:
    build:
      context: .
      dockerfile: ./apps/registry/Dockerfile
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - USERS_DB_URI=mongodb://users_db:27017
      - USERS_DB_NAME=usersDB

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - SECRET_KEY=shhhhh
      - USERS_DB_URI=mongodb://users_db:27017
      - USERS_DB_NAME=usersDB
